---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: demo
spec:
  encryptedData:
    password: AgBQkVXJbw+vjvKqQ1Vp8jKiiny/G0VvUqiasYQlDnFVmTcxKOYjIwG3AF9OKtB+VSh5Bodb1Vo2jKnzT4D/xiarq3RywNoaerMRhbd+TzVhM9bMwTQqrlkZt5kz8Yr5I+3r7HbqSJxZMl627uTHEIz1s+dO9qwVzz8QmapyW0u/5I5jQf3NN5l/s8r7XXsB4tDlDAP6iOvwFsAJfyRGwkQuzVg1XRZbvpxqmfDEpjWthwvlXOzxvipg1wmSX/BnPDLWZNhx9ARRh6tE/Im3KvXVir2pC1wBPwCy3BmWii4yVNmHWyuG5BoDr9yWGc4PcZkNYSX0zlC10UM2ZsHYeeQlBtsCKAWc/mI/I7yjOU0/0oeMUGYghDqDb9bAo7z1r8HiJdj8deLr7b9HhkW6m+qGb+DqjS2w7So5GZ3gE7BL6lWVwezJak3ECDvd/KHeqw28t/oWDgHC+R92pXQZN/0S1PBv8iMMHPRwAXE+jekDw0/FM/WVz9Pdq7eKuwn74ItWQiTCb9D6WbgamxfTK7PafFXPtjiM/KeAZ1+ZtIzbHkW/kWmJgGVhGP50wAXM0owhy6FEAwWiLR7LzOrFDKWFPfx60fnsevMCPchSeToT7dlMr9k8p28wjBMSIGmAroIajMCJl4m6pZedCtAOMjSU22GMuDYoEM8+1UpaJ7Ii2RVNdSeRK2zla+z4dpbQcEJ9kUOfecApOFRIt3MkgGGxkwg=
    postgres-password: AgBLJrdLD8+TWw8N68pHTpMi3lUgww7CLXAYADg547mivR8bmemF6sgQgEfOxbnybkZLaoQ5NFEi3EdFxo4VKNuE4UEWqGICwRby/ZDUPy7A7fbIJH4aof/kk6XukPLaOhj8i+yJnHehLDuzfJAFPKM7UqiTaqcl/NROpwE2aDrh52j37vtfj9kixZGAR8UotrheOlewVpipI0z+1XiIee9J22AosfUtpyHMxLoUlj8clkeRV+wwZiASUbKYLiEIRHwj13MGX+vsGNw23UJ0lOSUj83tSR0x4XC6YqgLIeDCioiaOhrP+7PWS+GwMyfSwIKxxUduIPjm8g9/wknBWwLYcmFkRfY7TTd4IvcRQ53S9PLFGCSbrw65yZI7J0vCTTwuOBCHM7q9ekQnOC9t2yLsxBNQtwmJFLs32QDdn0D70XxAQ34ARMslPQa9jVXKiicLuyWgKNwsWIUdYmMmhVYT1AP6zutvuvlF47dHeLljZ/7ulw78F/cXmlDtbdil7vkBGXPn46XivS/CHIWdeAznW8U8y4h+k/yUTO0Pp7LZxVVsI1W1SLx6UeGPrzUGsCE6MaWdzhxbhC5pAv8mh6qEgd05cELOcXxj2tUwDhxeoiJ1DJVNfX/xtFGArSpt9GSYAQicJhQVz19D0mz4y1loz1b2FFlleZ5Qf5wapagGb8g/heEmNWmvYyIGbgaQPC09Y20s2/5GdcnYHwNL9iqpLBSQg/I2
  template:
    metadata:
      name: postgres-secret
      namespace: demo
