apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-delivery-backend
  namespace: openshift-gitops
spec:
  project: demo
  source:
    repoURL: https://github.com/ssh-jmartinez/ocp-fullstack-gitops-delivery.git # Ajusta tu URL
    targetRevision: HEAD
    path: k8s-manifests/03-advanced-delivery/backend
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true