apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ssh-jmartinez/ocp-fullstack-gitops-delivery.git
    targetRevision: HEAD
    path: k8s-manifests/frontend
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {prune: true, selfHeal: true}