apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-demo
  namespace: openshift-gitops
spec:
  project: demo
  source:
    repoURL: https://github.com/ssh-jmartinez/ocp-fullstack-gitops-delivery.git
    targetRevision: HEAD
    path: pipelines/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {prune: true, selfHeal: true}